In [2]:
!python -m pip install --upgrade pip

zsh:1: command not found: python


In [3]:
import numpy as np

In [1]:
! pip3 install numpy

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.


In [20]:
x = np.array([1,2,3,4,5,6,7,8,9,10])
print(x)
print(type(x))
print(np.arange(10,20,3))
print(x.dtype)
print(np.zeros(5))
print(np.linspace(1,10,5))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
[10 13 16 19]
int64
[0. 0. 0. 0. 0.]
[ 1.    3.25  5.5   7.75 10.  ]


In [29]:
print(np.arange(1,11,1))
print(np.zeros((3,3)))
print(np.ones((3,3)))
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr[1:4,1:3])
print(arr[::2,::3])

[ 1  2  3  4  5  6  7  8  9 10]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 6  7]
 [10 11]
 [14 15]]
[[ 1  4]
 [ 9 12]]
